const NOT_AT_DESK = 'NOT_AT_DESK';
const MOBILE_DETECTED = 'MOBILE_DETECTED';
const MULTIPLE_PERSONS = 'MULTIPLE_PERSONS';
const UNKNOWN_USER = 'UNKNOWN_USER';
const SESSION_LOG_OFF = 'SESSION_LOG_OFF';
const DAY_LOG_OFF = 'DAY_LOG_OFF';
const USER_BACK_AT_DESK = 'USER_BACK_AT_DESK';
const AUTHORIZED_USER_BACK_AT_DESK = 'AUTHORIZED_USER_BACK_AT_DESK';
const DIGITS_COPIED = 'DIGITS_COPIED';
const LOGOUT = 'LOGOUT';
const SESSION_LOG_IN = 'SESSION_LOG_IN';
const BREAK_START = 'BREAK_START';
const BREAK_END = 'BREAK_END';

module.exports = {
  NOT_AT_DESK: NOT_AT_DESK,
  MOBILE_DETECTED: MOBILE_DETECTED,
  MULTIPLE_PERSONS: MULTIPLE_PERSONS,
  UNKNOWN_USER: UNKNOWN_USER,
  SESSION_LOG_OFF: SESSION_LOG_OFF,
  DAY_LOG_OFF: DAY_LOG_OFF,
  USER_BACK_AT_DESK: USER_BACK_AT_DESK,
  AUTHORIZED_USER_BACK_AT_DESK: AUTHORIZED_USER_BACK_AT_DESK,
  DIGITS_COPIED: DIGITS_COPIED,
  LOGOUT: LOGOUT,
  SESSION_LOG_IN: SESSION_LOG_IN,
  BREAK_START: BREAK_START,
  BREAK_END: BREAK_END,
};
